In [2]:
import numpy as np

In [3]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 3)

x_points, y_points = np.meshgrid(x, y)

In [4]:
values = np.ones(x_points.shape)

In [5]:
values

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
x_points

array([[ 0. ,  0.5,  1. ],
       [ 0. ,  0.5,  1. ],
       [ 0. ,  0.5,  1. ]])

In [7]:
values[1,1] = np.nan

In [18]:
values

array([[  1.,   1.,   1.],
       [  1.,  nan,   1.],
       [  1.,   1.,   1.]])

In [19]:
index_to_delete = np.isnan(values.ravel())

In [39]:
not index_to_delete.any()

False

In [25]:
interp_values = values.ravel()[~index_to_delete]
interp_x = x_points.ravel()[~index_to_delete]
interp_y = y_points.ravel()[~index_to_delete]


In [31]:
np.dstack((interp_x, interp_y))[0]

array([[ 0. ,  0. ],
       [ 0.5,  0. ],
       [ 1. ,  0. ],
       [ 0. ,  0.5],
       [ 1. ,  0.5],
       [ 0. ,  1. ],
       [ 0.5,  1. ],
       [ 1. ,  1. ]])

In [10]:
from scipy.interpolate import griddata

In [36]:
griddata((interp_x, interp_y), 
         interp_values,
         (x_points, y_points),
         method='cubic')

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])